name: Run

on:
  workflow_dispatch:

jobs:
  clone-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout from Git
        uses: actions/checkout@v2.3.4
      - name: Download latest config.json from Apple
        run: ./DownloadTouristDConfig.sh
