name: Run

on:
  schedule:
    - cron: "*/15 * * * *"

  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout from Git
        uses: actions/checkout@v2.3.4
      - name: Download latest config.json from Apple
        run: ./DownloadTouristDConfig.sh
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          delete-branch: true